version: '3.1'

services:
  theo:
    image: theo:test
    container_name: theo
    environment:
      - MODE=test
      - DB_STORAGE=":memory:"
      - ADMIN_TOKEN=${ADMIN_TOKEN}
      - CLIENT_TOKENS=${CLIENT_TOKENS}
