version: '3.1'

services:
  mysql-server-1:
    image: mysql/mysql-server:8.0
    command:
      - "mysqld"
      - "--server_id=1"
      - "--binlog_checksum=NONE"
      - "--gtid_mode=ON"
      - "--enforce_gtid_consistency=ON"
      - "--log_bin"
      - "--log_slave_updates=ON"
      - "--master_info_repository=TABLE"
      - "--relay_log_info_repository=TABLE"
      - "--transaction_write_set_extraction=XXHASH64"
      - "--user=mysql"
      - "--skip-host-cache"
      - "--skip-name-resolve"
      - "--default_authentication_plugin=mysql_native_password"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_ROOT_HOST: "%"
    ports:
      - 3301:3306
  mysql-server-2:
    image: mysql/mysql-server:8.0
    command:
      - "mysqld"
      - "--server_id=2"
      - "--binlog_checksum=NONE"
      - "--gtid_mode=ON"
      - "--enforce_gtid_consistency=ON"
      - "--log_bin"
      - "--log_slave_updates=ON"
      - "--master_info_repository=TABLE"
      - "--relay_log_info_repository=TABLE"
      - "--transaction_write_set_extraction=XXHASH64"
      - "--user=mysql"
      - "--skip-host-cache"
      - "--skip-name-resolve"
      - "--default_authentication_plugin=mysql_native_password"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_ROOT_HOST: "%"
    ports:
      - 3302:3306
  mysql-server-3:
    image: mysql/mysql-server:8.0
    command:
      - "mysqld"
      - "--server_id=3"
      - "--binlog_checksum=NONE"
      - "--gtid_mode=ON"
      - "--enforce_gtid_consistency=ON"
      - "--log_bin"
      - "--log_slave_updates=ON"
      - "--master_info_repository=TABLE"
      - "--relay_log_info_repository=TABLE"
      - "--transaction_write_set_extraction=XXHASH64"
      - "--user=mysql"
      - "--skip-host-cache"
      - "--skip-name-resolve"
      - "--default_authentication_plugin=mysql_native_password"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_ROOT_HOST: "%"
    ports:
      - 3303:3306
  mysql-shell:
    image: neumayer/mysql-shell-batch
    volumes:
      - ./scripts/:/scripts/
    depends_on:
      - mysql-server-1
      - mysql-server-2
      - mysql-server-3
    environment:
      MYSQL_USER: root
      MYSQL_HOST: mysql-server-1
      MYSQL_PORT: 3306
      MYSQL_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQLSH_SCRIPT: /scripts/setupCluster.js
      MYSQL_SCRIPT: /scripts/db.sql
  cache:
    image: redis:4.0-alpine
    ports:
      - 6379:6379
